=== NyBatis/NyBatisCore/schema/nybatis-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2012 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!ELEMENT configuration (properties?, environment*)>

  <!ELEMENT properties (property*)>
  <!ATTLIST properties
    path CDATA #IMPLIED
    >

    <!ELEMENT property EMPTY>
    <!ATTLIST property
      key CDATA #REQUIRED
      value CDATA #REQUIRED
      >


  <!ELEMENT environment (datasource, sqlpath?)>
  <!ATTLIST environment
    id CDATA #REQUIRED
    default (true|false) #IMPLIED
    >

  <!ELEMENT datasource ( driver, url, (username | password | timeout | autocommit ) | (initialContext , providerUrl), name )>
  <!ATTLIST datasource
    type      (jdbc|jndi) #REQUIRED
    poolMin   CDATA #IMPLIED
    poolMax   CDATA #IMPLIED
    poolStep  CDATA #IMPLIED
    ping      CDATA #IMPLIED
    pingCycle CDATA #IMPLIED
    >

    <!ELEMENT driver ANY>
    <!ELEMENT url ANY>
    <!ELEMENT username ANY>
    <!ELEMENT password ANY>
    <!ELEMENT timeout ANY>
    <!ELEMENT autocommit ANY>
    <!ELEMENT initialContext ANY>
    <!ELEMENT providerUrl ANY>
    <!ELEMENT name ANY>

  <!ELEMENT sqlpath ( path )>
    <!ELEMENT path ANY>

=== NyBatis/NyBatisCore/schema/config-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE configuration PUBLIC "-//nybatis.org//DTD Mapper 3.0//EN" "nybatis-config.dtd">-->
<!--<!DOCTYPE configuration SYSTEM "nybatis-config.dtd">-->

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="file:/C:\NIDE\workspace\NayasisCore\NyBatisCore\schema\nybatis-config.xsd">

  <properties path="config.properties">
    <property key="username" value="nayasis+#{driver}"/>
    <property key="password" value="F332459"/>
  </properties>

  <environment id="sample01" default="true">
    <datasource type="jdbc" poolMin="5" poolMax="20" poolStep="5" ping="true" pingCycle="60" >
      <driver>#{driver}</driver>
      <url>#{url}</url>
      <username>#{username}</username>
      <password>#{password}</password>
      <timeout>25</timeout> <!-- Optional -->
      <autocommit>false</autocommit> <!-- Optional -->
    </datasource>
    <sqlpath>
      <path>test01/sample.xml</path>
      <path>test02/sub01</path>
    </sqlpath>
  </environment>

  <environment id="sample02">
    <datasource type="jdbc">
      <driver>org.sqlite.JDBC</driver>
      <url>jdbc:sqlite:./target/test-classes/localDb/SimpleLauncherHelloWorld.db</url>
    </datasource>
    <sqlpath>
      <!--<path>test02/sub02</path>-->
      <!--<path>test02/sub02</path>-->
    </sqlpath>
  </environment>

  <environment id="sample03">
    <datasource type="jndi">
      <initialContext>....</initialContext>
      <providerUrl>....</providerUrl>
      <!-- it is possible to omit "java:comp/env/" -->
      <name>java:comp/env/Sample</name>
    </datasource>
    <sqlpath>
      <path>test03</path>
    </sqlpath>
  </environment>


</configuration>
