=== NyBatis/NyBatisCore/schema/nybatis-mapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Define root (mapper) -->

  <xs:element name="mapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sql" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueSqlId" >
      <xs:selector xpath="sql" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>


  <!-- Define sql -->

  <xs:element name="sql">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="key"      />
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="foreach"  />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
      <xs:attribute name="id"         type="notEmpty" use="required"/>
      <xs:attribute name="fetch"      type="xs:positiveInteger" />
      <xs:attribute name="cache"      type="notEmpty" />
      <xs:attribute name="flush"      type="xs:positiveInteger" />
      <xs:attribute name="autocommit" type="xs:boolean" />
    </xs:complexType>
  </xs:element>


  <!-- Define group -->

  <xs:group name="ifElse">
    <xs:sequence>
      <xs:element ref="if"     minOccurs="1" maxOccurs="1" />
      <xs:element ref="elseif" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="else"   minOccurs="0" maxOccurs="1"         />
    </xs:sequence>
  </xs:group>


  <!-- Define Sql Node -->

  <xs:element name="key">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="foreach"  />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="if">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="foreach"  />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
      <xs:attribute name="test" type="notEmpty" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="elseif">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="foreach"  />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
      <xs:attribute name="test" type="notEmpty" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="else">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="foreach"  />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="case">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="when" minOccurs="1" maxOccurs="unbounded" />
        <xs:element ref="else" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="when">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="foreach"  />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
      <xs:attribute name="test" type="notEmpty" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="foreach">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group   ref="ifElse"   />
        <xs:element ref="case"     />
        <xs:element ref="group"    />
        <xs:element ref="ref"      />
      </xs:choice>
      <xs:attribute name="key"       type="notEmpty" use="required" />
      <xs:attribute name="open"      type="notEmpty" />
      <xs:attribute name="close"     type="notEmpty" />
      <xs:attribute name="delimeter" type="notEmpty" />
      <xs:attribute name="indexKey"  type="notEmpty" />
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="if" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="open"      type="notEmpty" />
      <xs:attribute name="close"     type="notEmpty" />
      <xs:attribute name="delimeter" type="notEmpty" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ref">
    <xs:complexType>
      <xs:attribute name="id" type="notEmpty" use="required" />
    </xs:complexType>
  </xs:element>


  <!-- Validation -->

  <xs:simpleType name="notEmpty">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== NyBatis/NyBatisCore/schema/nybatis-mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nybatis-mapper.xsd">

<sql id="select" fetch="50" cache="notRegistered" flush="60" >
  SELECT  *
  FROM    PROD
  WHERE   list_id  = #{listId}
  <!-- AND     rownum  <= #{rowNum} -->
  ORDER BY ${orderKey}
  LIMIT 0, #{rowNum:int}
</sql>

  <sql id="select1" >
    SELECT * FROM TABLE
    <key id="11">aa
    </key>
    <ref id="22"/>
    <if test="111">
    </if>
    <if test="s"></if>
    <elseif test="aa"></elseif>
    <else></else>
    <if test="11">aa

    </if>

    <foreach key="dd"></foreach>
    <case>
      <when test="aa"></when>
      <else/>
    </case>
    <ref id="sss"></ref>
    <group>
      <if test="aa"></if>
    </group>
  </sql>

  <sql id="select02" fetch="50" cache="notRegistered" flush="60" >

  </sql>

<sql id="selectKey" fetch="50" cache="notRegistered" flush="60" autocommit="true" >
  <key id="listId">
    SELECT 'A001'
  </key>
  <key id="rowNum">
    SELECT 4
  </key>
  <key id="keyValue">
    SELECT 'keyValue' AS key
    UNION ALL
    SELECT list_id
    FROM   PROD
    LIMIT  0, #{rowNum}
  </key>
  SELECT  *, ${} "key_value"
  FROM    PROD
  WHERE   list_id = #{listId}
  LIMIT 0, #{rowNum}
</sql>

<sql id="insert" autocommit="true" >
INSERT
INTO   PROD
(
  list_id,
  prod_id,
  price,
  image
) VALUES (
  #{listId},
  #{prodId},
  #{price},
  #{image}
)
</sql>

<sql id="delete" >
DELETE
FROM    PROD
WHERE   list_id = #{listId}
</sql>

<sql id="refOrigin" >
  SELECT  *
  FROM    TB_DP_LIST_PROD
  WHERE   tenant_id = #{tenantId}
  ORDER BY ${orderKey}
</sql>

<sql id="refTestInvalid">
SELECT *
FROM
(
  <ref id="Sqlite.refOrigin2" />
)
WHERE rownum &lt;= 10
</sql>

<sql id="refTestValid">
SELECT *
FROM
(
  <ref id="Sqlite.refOrigin" />
)
WHERE rownum &lt;= 10
</sql>

<sql id="selectForParamTest" fetch="50" cache="fifo" flush="10" >
  SELECT  *
  FROM    PROD
  WHERE   list_id  =  #{listId}
  AND     ( prod_id  =  #{prodId} or prod_id = #{_globalSession_} )
  AND     price    >= #{price:int}
</sql>

<sql id="selectForList" fetch="50" cache="lru">
  SELECT  *
  FROM    PROD
  WHERE   list_id  =  #{listId}
  ORDER BY prod_id
</sql>

<sql id="selectWithoutParam" fetch="50" cache="fifo" flush="60" >
  SELECT  *
  FROM    PROD
  WHERE   list_id  = 'A001'
  ORDER BY prod_id
</sql>

<sql id="selectForMultiEnvironmentTest">
  SELECT * FROM NYBATIS_TEST
</sql>

</mapper>

=== NyBatis/NyBatisCore/src/test/resources/config/db/sqlite/Sqlite.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:nybatis.mapper:1.0" xsi:schemaLocation="urn:nybatis.mapper:1.0 http://nybatis.github.io/schema/nybatis-mapper.xsd">

<sql id="select" fetch="50" cache="notRegistered" flush="60" >
  SELECT  *
  FROM    PROD
  WHERE   list_id  = #{listId}
  <!-- AND     rownum  <= #{rowNum} -->
  ORDER BY ${orderKey}
  LIMIT 0, #{rowNum:int}
</sql>

<sql id="selectKey" fetch="50" cache="notRegistered" flush="60">
  <key id="listId">
    SELECT 'A001'
  </key>
  <key id="rowNum">
    SELECT 4
  </key>
  <key id="keyValue">
    SELECT 'keyValue' AS key
    UNION ALL
    SELECT list_id
    FROM   PROD
    LIMIT  0, #{rowNum}
  </key>
  SELECT  *, ${} "key_value"
  FROM    PROD
  WHERE   list_id = #{listId}
  LIMIT 0, #{rowNum}
</sql>

<sql id="insert">
INSERT
INTO   PROD
(
  list_id,
  prod_id,
  price,
  image
) VALUES (
  #{listId},
  #{prodId},
  #{price},
  #{image}
)
</sql>

<sql id="delete" >
DELETE
FROM    PROD
WHERE   list_id = #{listId}
</sql>

<sql id="refOrigin" >
  SELECT  *
  FROM    TB_DP_LIST_PROD
  WHERE   tenant_id = #{tenantId}
  ORDER BY ${orderKey}
</sql>

<sql id="refTestInvalid">
SELECT *
FROM
(
  <ref id="Sqlite.refOrigin2" />
)
WHERE rownum &lt;= 10
</sql>

<sql id="refTestValid">
SELECT *
FROM
(
  <ref id="Sqlite.refOrigin" />
)
WHERE rownum &lt;= 10
</sql>

<sql id="selectForParamTest" fetch="50" cache="fifo" flush="10" >
  SELECT  *
  FROM    PROD
  WHERE   list_id  =  #{listId}
  AND     ( prod_id  =  #{prodId} or prod_id = #{_globalSession_} )
  AND     price    >= #{price:int}
</sql>

<sql id="selectForList" fetch="50" cache="lru">
  SELECT  *
  FROM    PROD
  WHERE   list_id  =  #{listId}
  ORDER BY prod_id
</sql>

<sql id="selectWithoutParam" fetch="50" cache="fifo" flush="60" >
  SELECT  *
  FROM    PROD
  WHERE   list_id  = 'A001'
  ORDER BY prod_id
</sql>

<sql id="selectForMultiEnvironmentTest">
  SELECT * FROM NYBATIS_TEST
</sql>

</mapper>

=== NyBatis/NyBatisCore/src/test/resources/config/db/oracle/OracleTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:nybatis.mapper:1.2" xsi:schemaLocation="urn:nybatis.mapper:1.2 http://nybatis.github.io/schema/nybatis-mapper.xsd">

<!-- Retrieve Test -->

<sql id="select" fetch="50" cache="true" flush="60" >
  SELECT  *
  FROM    TB_DP_LIST_PROD
  WHERE   rownum &lt;= 10
</sql>

<sql id="dynamic" >
  SELECT  *
  FROM    TB_DP_LIST_PROD
  WHERE   tenant_id = #{tenantId}
  AND     rownum    &lt;= #{rowNum}
  ORDER BY ${orderKey}
</sql>

<sql id="dynamicError" >
  SELECT  *
  FROM    TB_DP_LIST_PROD
  WHERE   tenant_id = #{tenantId}
  AND     rownum    &lt;= #{rowNum}
  ORDER BY ${orderKey}
</sql>

<sql id="paged">
SELECT  *
FROM    TB_DP_LIST_PROD
WHERE   tenant_id = 'S01'
AND     list_id   = 'TGR000000001'
ORDER BY expo_ord, expo_ord_sub
</sql>


<!-- Function & Procedure Test -->

<sql id="selectCursor">
SELECT  test_function_01() AS rs
FROM    DUAL
</sql>

<sql id="procedure01" >
<!--
CREATE OR REPLACE PROCEDURE TEST_PROCEDURE_01(
     p_tenant_id IN  TB_DP_LIST.tenant_id%TYPE,
     p_list_id   IN  TB_DP_LIST.list_id%TYPE,
     o_list_nm   OUT TB_DP_LIST.list_nm%TYPE,
     o_cnt       OUT NUMBER
)
IS
BEGIN

  o_cnt := 7;

  SELECT  list_nm
  INTO    o_list_nm
  FROM    TB_DP_LIST
  WHERE   tenant_id = p_tenant_id
  AND     list_id   = p_list_id
  ;

END;
 -->
{ call TEST_PROCEDURE_01( #{tenantId}, #{listId}, #{listNm:out}, #{cnt:int:out} ) }
</sql>

<sql id="procedure02" >
<!--
CREATE OR REPLACE PROCEDURE TEST_PROCEDURE_02(
       o_cursor OUT SYS_REFCURSOR,
       o_cnt    OUT NUMBER
)
IS
BEGIN
    o_cnt := 7;
    OPEN o_cursor FOR SELECT * FROM TB_DP_LIST WHERE rownum < 10;
END;
 -->
{ call TEST_PROCEDURE_02( #{result:rs:out}, #{cnt:int:out} ) }
</sql>

<sql id="function01" >
<!--
CREATE OR REPLACE FUNCTION TEST_FUNCTION_01 RETURN SYS_REFCURSOR
AS
    l_cursor SYS_REFCURSOR;
BEGIN
    OPEN   l_cursor FOR SELECT * FROM TB_DP_LIST WHERE rownum < 10;
    RETURN l_cursor;
END;
 -->
{ #{result:sys_refcursor:out} = call TEST_FUNCTION_01() }
<!--
{ #{result:RS:out} = call TEST_FUNCTION_01() }
{ #{result:CURSOR:out} = call TEST_FUNCTION_01() }
{ #{result:SYS_REFCURSOR:out} = call TEST_FUNCTION_01() }
{ #{result:RESULTSET:out} = call TEST_FUNCTION_01() }
{ #{result:ORACLE_RESULTSET:out} = call TEST_FUNCTION_01() }
 -->

</sql>

<sql id="function01-NoOutReturn" >
<!--
CREATE OR REPLACE FUNCTION TEST_FUNCTION_01 RETURN SYS_REFCURSOR
AS
    l_cursor SYS_REFCURSOR;
BEGIN
    OPEN   l_cursor FOR SELECT * FROM TB_DP_LIST WHERE rownum < 10;
    RETURN l_cursor;
END;
 -->
{ call TEST_FUNCTION_01() } -- Oracle doesn't support function call having no result.
</sql>

<sql id="function02" >
<!--
CREATE OR REPLACE FUNCTION TEST_FUNCTION_02 RETURN VARCHAR
AS
BEGIN
    RETURN 'SUCCESS';
END;
 -->
{ #{result:out} = call TEST_FUNCTION_02() }
</sql>

</mapper>
